name: codyrogers
favicon: null
layout_spectrum: 0.9510638
typography_spectrum: 0.8344896202906966
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: the grid beta site
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.4774226390291005
  lightness: 0.6840021528769284
  saturation: 0.4243654599413276
  rhythmicContrast: 0.1714584613218904
purpose: []
