name: codyrogers
favicon: null
layout_spectrum: 0.76161
typography_spectrum: 0.20676
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Cody Rogers
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f6f6ee'
    - '#40456d'
    - '#28201b'
    - '#85b4bc'
    - '#6d8899'
  brandStrength: 0
  lightness: 1
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
